- docs/rest/compare-graph-outlook.md
Sync is now available in 1.0 Graph
> Update graph comparison doc

- docs/rest/dotnet-tutorial.md
The MSAL library was just released in preview, and they changed the way you work with the library. Updated tutorial to take this into account.
> Updated tutorial steps for MSAL preview

- docs/rest/node-tutorial.md
> Corrected initialization of simple-oauth2

- docs/rest/php-tutorial.md
Fixes #54.
Also did some cleanup of other missing bits.
> Adding missing use statements

- docs/rest/java-tutorial.md
Code snippet for saving tokens in session was outdated. Fixes #60.
> Correcting token storage

- docs/actionable-messages/actionable-messages-via-email.md
- Clarified limitation on sending actionable messages without registering
- Added note that actionable email must be HTML formatted
> Updates actionable message via email topic

- docs/add-ins/add-mobile-support.md
Was missing required `Group` element.
> Correcting example manifest snippet

- docs/actionable-messages/actionable-email-dev-dashboard.md
Updated guidelines for Office 365 and Outlook.com as well as a few industry guidelines to help 3rd party developers.
> Updated to include actual email guidelines

- docs/add-ins/addin-tutorial.md
- Added displayInIframe option to dialogs for better experience in browser
- Moved event.completed call until after the dialog is resolved
> Corrected tutorial code

- docs/rest/dotnet-tutorial.md
Reported by a user on the doc site.
> Made fixes to .NET tutorial

- docs/add-ins/index.md
- docs/add-ins/troubleshoot-outlook-add-in-activation.md
> Added custom form to the list of items add-ins do not activate for

- docs/actionable-messages/actionable-email-dev-dashboard.md
- docs/actionable-messages/index.md
- Added table of client versions that support actionable messages
> Actionable Message Updates

- docs/rest/node-tutorial.md
Based on changes to tutorial provided in https://github.com/jasonjoh/node-tutorial/pull/17
> Updated node tutorial

- docs/rest/php-tutorial.md
Changed "the the" to "the". Practicing my new docs editing.
> Removed a duplicate "the"

- docs/actionable-messages/index.md
Office 365 ProPlus Semi-Annual channel now supports actionable messages.
> Updated table of client versions

- docs/rest/javascript-tutorial.md
See https://github.com/jasonjoh/javascript-tutorial/issues/4
> Fixed getUserEmailAddress in JS tutorial

- .openpublishing.publish.config.json
- docs/add-ins/toc.yml
- docs/breadcrumb/toc.yml
- docs/context.yml
To properly test this TOC update I need to stage the update to master
> Attempting to add publish docs from Office site

- docs/rest/ruby-tutorial.md
The code you posted would not run, here are the lines that caused me trouble
> Missing helper line(s)

- docs/toc.yml
Clarifying that this is Outlook Documentation. It's much clearer and a pattern we're moving toward with the rest of the site. Email sabarret if you have any questions.
> Update the first node title

- docs/rest/dotnet-tutorial.md
Similar to fix reported by customer for Calendar
> Fixed file name

- docs/rest/node-tutorial.md
> Adding missing information

- docs/docfx.json
Enabling GitHub integration for feedback
> Feedback migration

- .gitattributes
- docs/rest/node-tutorial.md
> Corrected folder name in tutorial

- docs/actionable-messages/adaptive-card.md
- docs/actionable-messages/index.md
> Added version numbers for adaptive support

- docs/add-ins/get-attachments-of-an-outlook-item.md
> Replaced dead sample link

- docs/add-ins/use-rest-api.md
Addresses issue 140 in office-js repo: https://github.com/OfficeDev/office-js/issues/140
> address office-js issue 140

- docs/add-ins/web-services.md
Also took opportunity to clean up links so no longer redirecting
> update list of EWS methods supported by makeEwsRequestAsync API

- docs/add-ins/contextual-outlook-add-ins.md
Contextual activation is not yet available on all platforms. This should be clearly stated to set expectations.
> Platform specific information

- docs/payments/partner-dashboard.md
> Fixed broken link

- docs/add-ins/addin-tutorial.md
- docs/add-ins/quick-start.md
Updates to match editing feedback and be consistent with the rest of the Yo Office doc changes
> Editing Fix for Yo Office

- docs/add-ins/compose-scenario.md
https://github.com/OfficeDev/outlook-dev-docs/issues/283
> remove broken link

- docs/add-ins/addin-tutorial.md
> remove dupe line

- docs/actionable-messages/actionable-messages-via-email.md
Make the section title more friendly.
Update the add-in link from store to app source one, which supports work/school account
> Update section title and add-in link 

- docs/add-ins/use-rest-api.md
> added attachment ID info

- docs/add-ins/quick-start.md
Addresses issue https://github.com/OfficeDev/outlook-dev-docs/issues/340
> update add sub-folder for index.js

- docs/add-ins/quick-start.md
> add troubleshooting tips

- docs/add-ins/toc.yml
link to req. set 1.7 - pending https://github.com/OfficeDev/office-js-docs-reference/pull/174
> Outlook September updates

- docs/add-ins/quick-start.md
- docs/add-ins/troubleshoot-outlook-add-in-activation.md
Start addressing items raised in issue https://github.com/OfficeDev/outlook-dev-docs/issues/143.
Also minor fixes.
> Update quick start

- docs/add-ins/authenticate-a-user-with-an-sso-token.md
Related to issue https://github.com/OfficeDev/outlook-dev-docs/issues/350.
> Add resources for SSO auth

- docs/add-ins/add-in-commands-for-outlook.md
- docs/add-ins/add-mobile-support.md
- docs/add-ins/addin-tutorial.md
- docs/add-ins/manifests.md
- docs/add-ins/outlook-addin-design.md
- docs/add-ins/outlook-mobile-addins.md
- docs/add-ins/pinnable-taskpane.md
> Clean up taskpane

- docs/add-ins/manifests.md
Addresses issue https://github.com/OfficeDev/outlook-dev-docs/issues/432. Also includes some cleanup.
> Update hi-res to 128

- docs/add-ins/get-and-set-recurrence.md
- docs/add-ins/toc.yml
Note that this has already received technical review.
> Add recurrence article

- docs/add-ins/get-and-set-recurrence.md
Feedback on original PR: https://github.com/OfficeDev/outlook-dev-docs/pull/433/files
> Recurrence: Updates based on edit pass

- docs/add-ins/get-and-set-recurrence.md
- docs/add-ins/outlook-on-send-addins.md
- docs/add-ins/troubleshoot-outlook-add-in-activation.md
Recurrence topic updates
Validation warning notes
> merge to live

- docs/rest/compare-graph.md
- docs/rest/dotnet-tutorial.md
- docs/rest/java-tutorial.md
- docs/rest/node-tutorial.md
- docs/rest/php-tutorial.md
- docs/rest/python-tutorial.md
- docs/rest/ruby-tutorial.md
Replaced MSDN links
Made absolute links relative
Fixes #456
> Updated Azure docs links

- docs/add-ins/quick-start.md
Addresses issues #143 and #322.
> [Outlook] (quick start) Miscellaneous updates to code snippets and instructions.

- docs/actionable-messages/adaptive-card.md
- docs/actionable-messages/message-card-reference.md
Fixes #452 
Fixes #423 
Fixes #363
> Actionable message doc updates

- docs/add-ins/extension-module-outlook-add-ins.md
- docs/add-ins/pinnable-taskpane.md
> [Add-ins] (product support info) Indicate that features are supported in "Outlook 2016 or later"

- docs/add-ins/add-in-commands-for-outlook.md
Internal item: [2357047](https://office.visualstudio.com/OC/_workitems/edit/2357047)
> [Add-ins] Update default width of task pane

- docs/add-ins/add-in-commands-for-outlook.md
Related issue: https://github.com/OfficeDev/outlook-dev-docs/issues/498
> [Add-ins] Include links to VersionOverrides info

- docs/add-ins/use-rest-api.md
[Internal item](https://office.visualstudio.com/OC/_workitems/edit/2876922)
> [Add-ins] Clarify about Graph

- docs/add-ins/index.md
Addresses issue https://github.com/OfficeDev/outlook-dev-docs/issues/509.
> [Add-ins] Remove broken custom form link

- docs/add-ins/validate-an-identity-token.md
Addresses issue https://github.com/OfficeDev/outlook-dev-docs/issues/252
> [Add-ins] Add section on verifying domain

- docs/add-ins/pinnable-taskpane.md
[Internal item](https://office.visualstudio.com/OC/_workitems/edit/3013940)
> [Add-ins] No pinnable task panes in appointments

- docs/add-ins/add-mobile-support.md
Related issues:
https://github.com/OfficeDev/outlook-dev-docs/issues/520
https://github.com/OfficeDev/outlook-dev-docs/issues/492
> [Add-ins] Link to VersionOverrides

- docs/actionable-messages/security-requirements.md
- docs/add-ins/add-mobile-support.md
- docs/add-ins/outlook-on-send-addins.md
- docs/add-ins/pinnable-taskpane.md
- docs/add-ins/toc.yml
> merge to live!

- docs/add-ins/delegate-access.md
Related to issue https://github.com/OfficeDev/office-js-docs-pr/issues/863.
> [Add-ins] (delegate) Update ordering in manifest example

- docs/add-ins/outlook-on-send-addins.md
Should address issue https://github.com/OfficeDev/outlook-dev-docs/issues/539.
> [Add-ins] (on send) Update list of supported platforms

- docs/add-ins/outlook-on-send-addins.md
> [Add-ins] (on send) Update list of supported platforms (#556)

- docs/add-ins/addin-tutorial.md
- docs/add-ins/quick-start.md
Please note that I intentionally didn't update ms.date in either of these articles, since this isn't a substantive change.
> [Admin] Update language designation for command line code blocks.

- docs/add-ins/addin-tutorial.md
> [Outlook] (tutorial) Fix duplication issue

- docs/actionable-messages/index.md
- docs/add-ins/add-in-commands-for-outlook.md
- docs/add-ins/add-in-requirements.md
- docs/add-ins/add-mobile-support.md
- docs/add-ins/addin-tutorial.md
- docs/add-ins/compare-outlook-add-in-support-in-outlook-for-mac.md
- docs/add-ins/index.md
- docs/add-ins/pinnable-taskpane.md
- docs/add-ins/privacy-and-security.md
- docs/add-ins/sideload-outlook-add-ins-for-testing.md
- docs/add-ins/testing-and-tips.md
- docs/add-ins/troubleshoot-outlook-add-in-activation.md
See related PR https://github.com/OfficeDev/office-js-docs-pr/pull/994.
@jasonjoh: Please review non-add-ins changes. Thanks.
> Scrub product references

- docs/actionable-messages/security-requirements.md
- docs/add-ins/outlook-addin-design.md
> [Admin] (links) Fix broken links.

- docs/add-ins/addin-tutorial.md
- docs/add-ins/quick-start.md
Also a minor code change in the tutorial in response to Issue #328.
> [Add-ins] (tutorial & quickstart) Add Git to the list of prerequisites.

- docs/add-ins/authenticate-a-user-with-an-identity-token.md
- docs/add-ins/authentication.md
Related to issue https://github.com/OfficeDev/outlook-dev-docs/issues/593.
> [Add-ins] (Auth) Clarify getUserIdentityTokenAsync

- docs/add-ins/extension-module-outlook-add-ins.md
Addresses issue https://github.com/OfficeDev/outlook-dev-docs/issues/599.
> [Add-ins] (Module) Note Windows only

- docs/add-ins/outlook-on-send-addins.md
Related to issue https://github.com/OfficeDev/outlook-dev-docs/issues/639.
> [Add-ins] (on send) Specify which OWA is supported

- docs/add-ins/get-or-set-the-location-of-an-appointment.md
- docs/index.md
In cases where we talk about first add-in, link to quick start instead of tutorial
> [Add-ins] Update from tutorial to quick start

- docs/add-ins/delegate-access.md
* [Add-ins] (delegate) Note sync behavior
* Tweak
* Tweak note
> [Add-ins] (delegate) Note sync behavior (#655)

- docs/add-ins/add-and-remove-attachments-to-an-item-in-a-compose-form.md
- docs/add-ins/delegate-access.md
- docs/add-ins/get-or-set-the-location-of-an-appointment.md
* Initial
* Flesh out section on get methods
* Remove ms.topic
* Updates based on feedback
* Tweak
> [Add-ins] (attachments) Include preview APIs (#685)

- docs/actionable-messages/message-card-reference.md
> Corrected case of HttpPOST action in list of actions

- docs/add-ins/add-and-remove-attachments-to-an-item-in-a-compose-form.md
- docs/add-ins/get-or-set-the-location-of-an-appointment.md
- docs/add-ins/outlook-on-send-addins.md
Fixes https://github.com/OfficeDev/outlook-dev-docs/issues/709
> [Add-ins] Link to preview reqt. set page

- docs/add-ins/manifests.md
Fixes https://github.com/OfficeDev/outlook-dev-docs/issues/715.
> [Add-ins] (manifest) Update to valid example

- docs/rest/node-tutorial.md
'var index' is now 'var indexRouter' for example
> Update node-tutorial.md to match generated code

- docs/add-ins/add-in-requirements.md
- docs/add-ins/add-mobile-support.md
- docs/add-ins/contextual-outlook-add-ins.md
- docs/add-ins/index.md
* [Add-ins] Update clients anchor
* Update dates
> [Add-ins] Update clients anchor (#730)

- docs/add-ins/addin-tutorial.md
- docs/add-ins/index.md
- docs/add-ins/quick-start.md
Related to https://github.com/OfficeDev/office-js-docs-pr/pull/1350.
> [Add-ins] Update metadata in getting-started docs.

- docs/add-ins/use-rest-api.md
Also, minor punctuation clean up in samples.
> [Add-ins] (samples) Update to absolute link

- docs/add-ins/internet-headers.md
- docs/add-ins/toc.yml
* [Outlook] (preview) Add internet headers article
* Update metadata
* Remove comma
* Update casing
* Add read sample
* Updates based on feedback
* Update samples
* Fix typos
* Update read sample
* Tweak
* Update name format per feedback
* Updates based on feedback
* Remove extra close comment
* Tweak
* Apply suggestions from code review
Co-Authored-By: Linda Lu Cannon <lindalu@microsoft.com>
* Tweak note
* Update ms.date
> [Add-ins] Add internet headers article (#743)

- docs/add-ins/outlook-on-send-addins.md
* [Add-ins] Remove Events-specific text
* On-send add-ins not allowed in the store
* Add important note
> [Add-ins] Remove Events-specific text (#751)

- docs/add-ins/outlook-on-send-addins.md
Fixes https://github.com/OfficeDev/outlook-dev-docs/issues/760.
> [Add-ins] Refine note about on-send support

- docs/actionable-messages/message-card-reference.md
> Corrected number of action types

- docs/add-ins/addin-tutorial.md
- docs/add-ins/quick-start.md
> [Add-ins] (quick start & tutorial) Update the command that's used to start the web server.

- docs/add-ins/quick-start.md
- docs/amphtml/index.md
This PR updates the Outlook add-in quick start to specify different content in the **Next steps** section depending on whether guidance being shown is for the Yeoman generator or Visual Studio.
> [Add-ins] (Visual Studio) Update guidance related to developing add-ins with Visual Studio.

- docs/actionable-messages/send-via-connectors.md
> Added note that connectors do not support Adaptive Card

- docs/add-ins/get-attachments-of-an-outlook-item.md
Fixes https://github.com/OfficeDev/outlook-dev-docs/issues/798.
> [Add-ins] (attachments) Remove extra code from sample

- docs/add-ins/addin-tutorial.md
- docs/add-ins/quick-start.md
Changes made per internal work item # 3890206.
Articles impacted by this change include the Add-ins quick start and tutorial.
> [Add-ins] (Yo Office) Add info re the required version of Node.js.

- docs/actionable-messages/adaptive-card.md
- docs/actionable-messages/toc.yml
> Corrected link to adaptive card designer tool

- docs/actionable-messages/email-dev-dashboard.md
> Corrected verification email address

- docs/actionable-messages/identity-linking.md
> Updated client support roadmap for identity linking

- docs/actionable-messages/identity-linking.md
> Corrected header name for identity linking feature

- docs/actionable-messages/index.md
- Outlook 2016 on Mac now supports AM
- Outlook on Android now supports AM
- Note about sync tech no longer needed
> Updated version table

- docs/actionable-messages/index.md
> Added note to specify Office 2016 supports AM only in C2R installs

- docs/actionable-messages/auto-invoke.md
> Added requirement to contact onboarding team to enable auto-invoke

- docs/actionable-messages/adaptive-card.md
- docs/actionable-messages/connectors-dev-dashboard.md
- docs/actionable-messages/email-dev-dashboard.md
- docs/actionable-messages/get-started.md
- docs/actionable-messages/index.md
Monthly link cleanup.
/cc @jasonjoh
> Links: Outlook Dev (2021-02)

- docs/actionable-messages/send-via-connectors.md
Update the doc description on Microsoft 365 developer subscription.
> fix: developer subscription is no longer 1 year

- docs/actionable-messages/security-requirements.md
> Added metadata URL and token issuer

- docs/actionable-messages/email-dev-dashboard.md
- docs/rest/compare-graph.md
> Misc Fixes

- docs/rest/compare-graph.md
> Add note that Outlook APIs are deprecated across all versions

- docs/actionable-messages/email-dev-dashboard.md
I spent a few hours trying to fix an error that wasn't there, I just had to wait for changes to propagate after submitting my connector. If someone can help with the wording and improve it then I'm sure this warning will help other developers save some time.
> Warning for developers to wait after submission

- README.md
- docs/actionable-messages/message-card-reference.md
- docs/actionable-messages/send-via-connectors.md
- docs/actionable-messages/send-via-email.md
**Global effort for the Microsoft Learn platform rebrand**
The Microsoft team is applying changes to content for the Microsoft Learn platform rebrand. Changes include modifications to current Microsoft Learn and Microsoft Docs terminology as well as associated domain name and content URL path changes.
Please review this draft PR and provide any necessary comments as soon as possible. Because these fixes are tightly scoped, we have approval to automatically merge these changes to the default branch for publication.
This PR was generated via DocuTune. It includes only targeted fixes and minor formatting adjustments.
CorrelationId: d8c4c3ac-d49a-4c95-9ddc-9822ca297907
InitiativeId: docutune-rebranding-2022-09
PointOfContact: Alex Buck
> [BULK UPDATE] DocuTune - Rebranding

- docs/actionable-messages/index.md
Updated download header preference for AM.
> Download Header preference.

- docs/index.md
- docs/rest/compare-graph.md
- docs/rest/concepts.md
- docs/rest/get-started.md
- docs/rest/index.md
- docs/rest/reference.md
A Pull Request has been made from the **Learn Platform's Metadata Management System**. Please review and merge this Pull Request within **5 days**. If you have any questions or concerns about the purpose of these metadata updates, please contact docs-allowlist-mgmt@microsoft.com. If you are not the correct contact for this content and repository, please notify Learn-Metadata-Admin@microsoft.com. 
If this Pull Request is not merged within **14 days**, it will be automatically merged by our system to ensure the timeliness of the metadata update. **This includes bypassing the Repository's Branch Policy, including if Review Required is enabled**. Please notify Learn-Metadata-Admin@microsoft.com if you have questions or concerns or would like Pull Requests for metadata updates to merge …
> [METADATA UPDATE] Global metadata/header/navigation changes

- docs/actionable-messages/index.md
- docs/actionable-messages/universal-action-model.md
> Updated supported versions

- docs/actionable-messages/actionable-messages-faq.md
- docs/includes/actionable-messages/global-onboarding-paused-notice.md
After discussion with engineering, Changing the date to Jun 30th. 2024.
> Change date

- docs/actionable-messages/index.md
Publish this PR [Update index.md by MinaNagui · Pull Request #1051 · OfficeDev/outlook-dev-docs · GitHub](https://github.com/OfficeDev/outlook-dev-docs/pull/1051)
> [admin] merge to live

- .github/workflows/auto-publish.yml
Should publish around 3:45 PM PST / 4:45 PM PDT on Wednesdays
> Add auto-publish workflow

- docs/actionable-messages/adaptive-card-expense-approval-sample.md
> Fix dead link to sample json file
