docs/includes/rest/app-registration-intro.md
docs/rest/index.md

All Outlook.com accounts now support the REST API, so removed the note about migration.

Removed note about Outlook.com accounts

---

docs/actionable-messages/card-reference.md

The `header` field in `HttpPOST` was documented as an array of strings, but it is actually an array of name/value pairs.

Correcting header reference

---

docs/add-ins/quick-start.md
docs/add-ins/toc.yml

Minor changes to make the Outlook quickstart consistent with Add-in quickstarts for other Office products:
- Changed wording from "write" to "build".
- Added button to Next steps section of Outlook quickstart.

Minor changes to Outlook quickstart and its TOC entry.

---

docs/docfx.json

Changed ms.suite tag to 'office365' so that all docs are using the same value and appear in reports together.

applying office365 tag

---

docs/actionable-messages/invoke-add-in-from-actionable-message.md

The original sample markup was just for the action portion of a card, not a full card. This was causing confusion when readers were trying this feature out in the playground. Added minimal surrounding markup to make it a full card.

Updated sample card markup to include minimum required markup

---

.openpublishing.publish.config.json

I’ve noticed in another PR that you had to manually change the branch to master because docs is pointing to live. This should fix that problem.

Making master the default branch from docs

---

docs/rest/dotnet-tutorial.md
docs/rest/ios-tutorial.md
docs/rest/java-tutorial.md
docs/rest/javascript-tutorial.md
docs/rest/node-tutorial.md
docs/rest/php-tutorial.md
docs/rest/python-tutorial.md
docs/rest/ruby-tutorial.md

Graph ignores this header, so setting it was useless. Removing this allowed the tutorials to be simplified and shortened.

Removed X-AnchorMailbox from REST tutorials

---

docs/add-ins/use-rest-api.md

Correct typo in the url for the endpoint: `restUrl` already contains `'/api'`, so this is removed and `'/me'` is required in the url path right before `'/message'`

Fixes #199: typo in url for endpoint

---

docs/rest/dotnet-tutorial.md

Wrong file was mentioned. AzureOauth.config was referenced in the web.config before so the setting is to be updated there.

Calendar API AppScopes in dotnet-tutorial.md

---

.openpublishing.build.ps1

PowerShell by default uses TLS 1.0 for all Rest API requests, which is vulnerable to [POODLE](https://githubengineering.com/crypto-deprecation-notice/) and other crypto vulnerabilities. Applying this change will force supporting TLS 1.2 and prevent having the following error:
```PowerShell
The request was aborted: Could not create SSL/TLS secure channel.
```
This update also (permanently) fixes [#358](https://github.com/OfficeDev/outlook-dev-docs/issues/358), which worked on Azure portal since TLS 1.2 is already supported there.

Support TLS 1.2

---

docs/add-ins/use-regular-expressions-to-show-an-outlook-add-in.md

Fix typo in 'Use regular expression activation rules to show an Outlook add-in' article

---

docs/add-ins/addin-tutorial.md
docs/add-ins/toc.yml

OPS didn't refresh the TOC when the docs were merged to **live** a few minutes ago. Whenever this happens, simply merging another PR usually fixes the problem.

[Outlook] (n/a) - Minor update to trigger rebuild of doc set

---

docs/actionable-messages/index.md

Adaptive Cards are supported in Office365 ProPlus Semi-Annual Channel (Targeted) from Version 1808, Build 10730.20262 and in Office365 ProPlus Semi-Annual Chanel from Version 1808, Build 10730.20264.

Update Adaptive Card support for Semi-Annual Channel

---

docs/actionable-messages/toc.yml
docs/add-ins/toc.yml
docs/rest/toc.yml

These changes are necessary due to an upcoming change in the way that OPS builds (renders) the TOC. For details, see internal work item # 3292909. 
I've used "Overview" as the name of the new child node, in most cases -- except for cases where "Overview" would insufficiently describe the content of the corresponding article (then I gave the node a more specific name).
(@jasonjoh - FYI, this PR updates a few nodes in the Actionable messages and REST APIs sections of the TOC as well.)

[Admin] (TOC) Ensure that parent nodes in the TOC never have an href.

---

docs/add-ins/addin-tutorial.md
docs/add-ins/quick-start.md

Addresses this issue: https://github.com/OfficeDev/office-js-docs-pr/issues/978.

[Add-ins] (certificate guidance) Update certificate guidance in Outlook quick start and tutorial.

---

docs/add-ins/addin-tutorial.md
docs/add-ins/quick-start.md

The next release of Yo Office no longer requires Git. I'll plan to merge this PR as soon as the next release of Yo Office is published (most likely Monday 6/24).

[Outlook] (Yo Office prerequisites) Remove Git as a prerequisite for using Yo Office.

---

docs/actionable-messages/invoke-add-in.md
docs/add-ins/add-in-requirements.md
docs/add-ins/apis.md
docs/add-ins/authenticate-a-user-with-an-sso-token.md
docs/add-ins/index.md
docs/add-ins/outlook-mobile-addins.md
docs/add-ins/outlook-on-send-addins.md
docs/add-ins/pinnable-taskpane.md
docs/add-ins/privacy-and-security.md
docs/add-ins/testing-and-tips.md
docs/add-ins/understanding-outlook-add-in-permissions.md

Changes **Office Store** -> **AppSource** and **side-load** -> **sideload** throughout the docs, and also fixes code formatting issues in the **On Send** article. Note that I've intentionally *not* updated `ms.date` in any of these articles, since none of the changes are substantive.

[Admin] Fix typos.

---

docs/actionable-messages/send-via-email.md

The link to the Office 365 SMTP page didn't actually contain the SMTP settings, only POP and IMAP. Updating the link to an article which does contain the Office 365 SMTP Server settings.

Updating Office 365 SMTP Server link

---

docs/add-ins/addin-tutorial.md
docs/add-ins/quick-start.md
docs/includes/note-yeoman-generator-bug-201908.md

This PR adds a note to call out a bug that's currently present in the Yeoman generator for Office Add-ins: OfficeDev/generator-office#476. It also removes the screenshots of Yo Office prompts (since screenshots show a currently-unpermitted value for project name). When the bug in Yo Office is fixed, we'll remove this note and restore the screenshot in each article that's updated by this PR.

[Add-ins] (Yo Office) Add note about spaces not being permitted in project name or folder path.

---

docs/add-ins/addin-tutorial.md
docs/add-ins/quick-start.md
docs/includes/note-yeoman-generator-bug-201908.md

This PR reverts changes made in PR #670 (now that the issue with spaces not being allowed in project names / folder paths has been resolved).

[Add-ins] (Yo Office) Remove note about spaces not being permitted in project name or folder path.

---

docs/add-ins/addin-tutorial.md

This portion of the tutorial is no longer required, since new(er) version of Yo Office creates the project with `SupportUrl` already populated in the manifest.

[Add-ins] (tutorial) Remove section about adding support page info.

---

docs/add-ins/addin-tutorial.md
docs/add-ins/quick-start.md
docs/includes/yo-office-command-guidance.md
docs/includes/yo-office-next-steps.md

This PR adds a couple of new notes to each article that contains instructions for using Yo Office -- a note about telemetry prompts, and a tip about ignoring 'next steps'. (Corresponding changes have been made in OfficeDev/office-js-docs-pr as part of this PR: https://github.com/OfficeDev/office-js-docs-pr/pull/1304.)

[Add-ins] (Yo Office guidance) Add notes about telemetry prompts and next steps guidance.

---

docs/rest/node-tutorial.md

Working my way through the tutorial and as it stands right now, when you implement the "Using the Mail API" section clicking on the "Mail" option in the toolbar will result in the below errors.
(node:9236) UnhandledPromiseRejectionWarning: PolyFillNotAvailable: Library cannot function without fetch. So, please provide polyfill for it.
at Object.exports.validatePolyFilling (f:\Version Control\node-tutorial\node_modules\@microsoft\microsoft-graph-client\lib\src\ValidatePolyFilling.js:27:21)
at new Client (f:\Version Control\node-tutorial\node_modules\@microsoft\microsoft-graph-client\lib\src\Client.js:36:35)
at Function.Client.initWithMiddleware (f:\Version Control\node-tutorial\node_modules\@microsoft\microsoft-graph-client\lib\src\Client.js:92:20)
at Function.Client.init (f:\Version …

Fix for "Library cannot function without fetch"

---

docs/add-ins/categories.md

Each of the 3 `items.categories` hyperlinks in the [Get or set categories](https://docs.microsoft.com/en-us/outlook/add-ins/categories) article points to the URL https://docs.microsoft.com/en-us/javascript/api/outlook/office.item#categories – but the `#categories` bookmark doesn’t exist on that page, so it’s causing an “Invalid bookmark” error in the CATS report.
This PR removes the hyperlink altogether in each of these 3 instances (and just formats `item.categories` as code instead).

[Add-ins] Fix CATS issues (January 2020)

---

docs/actionable-messages/security-requirements.md

Claim is not sent when message is received via connector.
This issue was reported in https://github.com/OfficeDev/outlook-actionable-messages-csharp-token-validation/issues/9

Added note about sender claim in bearer token

---

docs/actionable-messages/auto-invoke.md

The doc was missing a crucial part of the update response required by Outlook - header `CARD-UPDATE-IN-BODY` with value set to `true`, otherwise the response was being returned as `null`.

Include information about required header

---

docs/actionable-messages/invoke-add-in.md

Updates the getInitializationContextAsync snippet as the 9020 error is no longer returned when there is no initialization context. Related change: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63441.

Update snippet for getInitializationContextAsync
